"""Added color

Revision ID: 807e00921abb
Revises: ddd5d143400a
Create Date: 2026-03-30 18:36:51.679114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807e00921abb'
down_revision: Union[str, Sequence[str], None] = 'ddd5d143400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'current_clocks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'goals', 'tasks', ['tasks_id'], ['id'])
    op.create_foreign_key(None, 'historic_clocks', 'tasks', ['tasks_id'], ['id'])
    op.add_column('tasks', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'color')
    op.drop_constraint(None, 'historic_clocks', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'current_clocks', type_='foreignkey')
    # ### end Alembic commands ###
