"""Initial Migration

Revision ID: ddd5d143400a
Revises: 
Create Date: 2026-03-30 18:23:37.411796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd5d143400a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True, foreign_key='tasks.id'),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=True, foreign_key='tasks.id'),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target_hours', sa.Integer(), nullable=True),
    sa.Column('by_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historic_clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_id', sa.Integer(), nullable=True, foreign_key='tasks.id'),
    sa.Column('total_sec', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('historic_clocks')
    op.drop_table('goals')
    op.drop_table('current_clocks')
    # ### end Alembic commands ###
